import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CoinMarketProvider } from '@/context/context'
import { AppProps } from 'next/app'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <CoinMarketProvider>
      <Component {...pageProps}/>
    </CoinMarketProvider>
  )
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
